services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - frontend/.env.local
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3004:3004'
    env_file:
      - backend/.env.local
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_NAME: dev
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0.15
    container_name: github-crm-mongo-local
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: github-crm
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
